<script setup lang="ts">
import { computed, ref } from 'vue'
import { DataAnalysis, Files, Setting, Lock, ArrowRight, Monitor, RefreshRight } from '@element-plus/icons-vue'
const api = import.meta.env.VITE_API_BASE || '/api/console/v1'
const accessKey = ref(sessionStorage.getItem('console-key') || ''); const active = ref('overview'); const error = ref(''); const loading = ref(false); const overview = ref<any>(null); const tasks = ref<any[]>([]); const config = ref<any>(null)
const title = computed(() => ({ overview: '运行总览', tasks: '任务执行记录', config: '运行配置' }[active.value] || '运行总览'))
async function login() { loading.value = true; error.value = ''; try { const response = await fetch(`${api}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ accessKey: accessKey.value }) }); if (!response.ok) throw new Error('访问密钥无效，请联系系统管理员。'); sessionStorage.setItem('console-key', accessKey.value); await load() } catch (e) { error.value = e instanceof Error ? e.message : '登录失败' } finally { loading.value = false } }
async function load() { if (!accessKey.value) return; loading.value = true; try { const path = active.value === 'overview' ? 'overview' : active.value === 'tasks' ? 'tasks' : 'runtime-config'; const response = await fetch(`${api}/${path}`, { headers: { 'X-Console-Key': accessKey.value } }); if (!response.ok) throw new Error('会话已失效，请重新登录。'); const data = await response.json(); if (active.value === 'overview') overview.value = data; if (active.value === 'tasks') tasks.value = data; if (active.value === 'config') config.value = data; } catch (e) { error.value = e instanceof Error ? e.message : '加载失败' } finally { loading.value = false } }
function navigate(value: string) { active.value = value; error.value = ''; load() }
function logout() { sessionStorage.removeItem('console-key'); accessKey.value = ''; overview.value = null; tasks.value = [] }
if (accessKey.value) load()
</script>

<template>
  <div v-if="!accessKey || (!overview && !loading && error)" class="login-page">
    <section class="login-context"><div class="login-brand"><span>AT</span> Agent Template Pro</div><div class="context-copy"><p class="eyebrow">LOCAL / SECURE ACCESS</p><h1>把自然语言交互置于可控运行之中。</h1><p>查看会话任务、动作确认和运行状态。管理端与匿名访客会话严格隔离。</p></div><div class="preview"><div class="preview-head"><b>运行概览</b><span>健康</span></div><div class="preview-grid"><div><small>动作任务</small><strong>128</strong></div><div><small>成功率</small><strong>99.2%</strong></div></div><div class="preview-lines"><i></i><i></i><i></i></div></div></section>
    <section class="login-form-wrap"><form class="login-form" @submit.prevent="login"><div class="mobile-brand"><span>AT</span> Agent Template Pro</div><p class="eyebrow">身份验证 · AUTHENTICATION</p><h2>登录管理后台</h2><p class="form-copy">请输入环境配置的 Console 访问密钥。</p><el-alert v-if="error" :title="error" type="error" :closable="false" show-icon /><label for="access-key">访问密钥</label><el-input id="access-key" v-model="accessKey" type="password" show-password autocomplete="current-password" placeholder="Console access key" :disabled="loading" /><el-button native-type="submit" type="primary" :loading="loading">进入控制台 <el-icon><ArrowRight /></el-icon></el-button><p class="security-note"><el-icon><Lock /></el-icon> 本地示例使用访问密钥；生产环境请接入独立管理员认证和 RBAC。</p></form></section>
  </div>
  <div v-else class="console-shell">
    <aside class="sidebar"><div class="sidebar-brand"><span>AT</span><b>Agent<br/>Template</b></div><nav><button :class="{active:active==='overview'}" @click="navigate('overview')"><el-icon><DataAnalysis/></el-icon><span>运行总览</span></button><button :class="{active:active==='tasks'}" @click="navigate('tasks')"><el-icon><Files/></el-icon><span>任务记录</span></button><button :class="{active:active==='config'}" @click="navigate('config')"><el-icon><Setting/></el-icon><span>运行配置</span></button></nav><div class="sidebar-bottom"><span><i></i>本地演示环境</span><button @click="logout">退出</button></div></aside>
    <main class="workspace"><header class="workspace-header"><div><p class="eyebrow">AGENT RUNTIME / {{ active.toUpperCase() }}</p><h1>{{ title }}</h1></div><div class="header-actions"><el-button circle aria-label="刷新" :loading="loading" @click="load"><el-icon><RefreshRight/></el-icon></el-button><el-button type="primary" @click="navigate('tasks')">查看任务</el-button></div></header><p v-if="error" class="page-error">{{ error }}</p>
      <section v-if="active==='overview'" class="overview"><div class="metric-grid"><article><span>运行状态</span><strong class="healthy">{{ overview?.health || '-' }}</strong><small>服务可用性摘要</small></article><article><span>任务总数</span><strong>{{ overview?.taskTotal ?? '-' }}</strong><small>当前运行内存中的任务</small></article><article><span>等待中</span><strong>{{ overview?.activeTasks ?? '-' }}</strong><small>等待外部结果或用户确认</small></article></div><section class="operation-panel"><div class="panel-header"><div><h2>运行边界</h2><p>模型提出意图，确定性动作负责校验、确认和执行。</p></div><el-tag type="success" effect="plain">{{ overview?.mode || 'loading' }}</el-tag></div><div class="boundary-grid"><div><span>身份</span><b>签名访客 Cookie</b></div><div><span>会话</span><b>服务端归属校验</b></div><div><span>高风险动作</span><b>强制二次确认</b></div></div></section></section>
      <section v-if="active==='tasks'" class="table-section"><div class="table-toolbar"><div><h2>任务执行记录</h2><p>确认、调用和异步状态均以任务为追踪入口。</p></div><el-button @click="load">刷新列表</el-button></div><el-table :data="tasks" v-loading="loading" empty-text="暂无任务记录"><el-table-column prop="id" label="任务 ID" min-width="180" show-overflow-tooltip /><el-table-column prop="actionCode" label="动作" min-width="190" /><el-table-column label="状态" width="190"><template #default="scope"><el-tag :type="scope.row.status === 'SUCCEEDED' ? 'success' : scope.row.status.includes('WAITING') ? 'warning' : 'info'">{{ scope.row.status }}</el-tag></template></el-table-column><el-table-column prop="externalRef" label="外部引用" min-width="160" /><el-table-column prop="createdAt" label="创建时间" min-width="180" /></el-table></section>
      <section v-if="active==='config'" class="config-section"><div class="panel-header"><div><h2>非敏感运行配置</h2><p>密钥和值不会通过控制台 API 返回。</p></div><el-icon class="monitor"><Monitor/></el-icon></div><dl v-if="config"><template v-for="(value,key) in config" :key="key"><dt>{{ key }}</dt><dd>{{ value }}</dd></template></dl></section>
    </main>
  </div>
</template>
