package com.manzhushaka.agent.common.error;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    CONVERSATION_FORBIDDEN,
    TASK_CONFIRMATION_CONFLICT,
    VALIDATION_FAILED,
    REQUEST_DUPLICATED,
    AGENT_NOT_FOUND,
    AGENT_DISABLED,
    AGENT_ROUTE_AMBIGUOUS,
    AGENT_ACTION_OWNERSHIP_INVALID,
    AGENT_SWITCH_BLOCKED_BY_PENDING_ACTION,
    AGENT_ROUTE_VERSION_CONFLICT
}
